### ISSUE TITLE
Loss NaN in Mamba2

### ISSUE THREAD

**Issue by tyshiwo1** [state-spaces/mamba#352] opened 2024-06-04 08:06 UTC
Hello guys,

When I applied Mamba2 to image generation, I found several NaN values in the gradients (`ddt_bias`, `dx`, and `ddt_given`) in `_mamba_chunk_scan_combined_bwd` of `mamba_ssm/ops/triton/ssd_combined.py`, therefore the loss is NaN.

The image generation code is [DiM](https://github.com/tyshiwo1/DiM-DiffusionMamba). I just replaced the original Mamba-1 block with Mamba-2. I used the bf16 precision for training from scratch, and the NaN appears in the first training iteration.

My environment is `triton==2.2.0, torch==2.2.1+cu121`.

If anyone can help me, I will be very grateful!
![nan](https://github.com/state-spaces/mamba/assets/34150970/67a49ceb-deb3-457e-986a-7eaaa113770e)

**Comment by zzzendurance** [comment] 2024-06-04 09:05
很抱歉打扰你，我没有遇到和你一样的问题，但是我想请教你一些问题。

1.你有没有遇到下面这种问题。
File "/data/zh/miniconda3/envs/man/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 113, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/data/zh/wa1/-main/IP/mamba/mamba_ssm/ops/triton/ssd_combined.py", line 757, in forward
    causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"),
TypeError: causal_conv1d_fwd(): incompatible function arguments. The following argument types are supported:
   (arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: Optional[torch.Tensor], arg4: bool) -> torch.Tensor
 这个我查到是因为causal_conv1d版本问题，我的causal_conv1d版本原本是1.1.1，我在更换版本为1.0.2后，他依旧报错。你的causal_conv1d版本是什么？

2.mamba2你是怎么直接用于自己项目的？是下载他那个whl文件，然后更新你虚拟环境中的mamba_ssm包吗？还是下载他整个项目文件，然后用的是项目文件里的mamba2文件？
如果你下载的是whl文件，那你是怎么选版本的？这里的abi 真否有何区别
mamba ssm-2.0.3+cu118torch1.13cxx11abiTRUE-cp310-cp310-inux x86 64.whl
mamba ssm-2.0.3+cu118torch1.13cxx11abiFALSE-cp310-cp310-inux x86 64.whl


很抱歉打扰你，期待回复捏~

**Comment by tyshiwo1** [comment] 2024-06-04 09:06
1. my casual conv 1d version is 1.2.0post1
2. I download the whole project and compile it locally using `CAUSAL_CONV1D_FORCE_BUILD=TRUE pip install --user -e .`

**Comment by zzzendurance** [comment] 2024-06-04 09:15
![nan](https://github.com/state-spaces/mamba/assets/156890826/b53d93dd-eb77-4220-b99e-a263c8683e21)
哈哈哈哈 ，感谢，我更新了我的casual conv 1d version为1.2.2.post1，成功跑起来了，然后遇到了和你一样的问题？之前mamba1同样的超参数没有nan过好像

**Comment by tyshiwo1** [comment] 2024-06-04 10:09
I found this line of code causes NaN of `dx`

https://github.com/state-spaces/mamba/blob/main/mamba_ssm/ops/triton/ssd_combined.py#L176

**Comment by Kiet0712** [comment] 2024-06-04 10:15
have you try to use float32 instead of bfloat16 ?

**Comment by tyshiwo1** [comment] 2024-06-04 10:26
> have you try to use float32 instead of bfloat16 ?

The NaN remains when I use fp32 to train.

**Comment by zzzendurance** [comment] 2024-06-04 10:43
wow，Do you know how to change this line of code (acc += tl.dot(cb, dout)) to solve the nan problem? (I'm so bad at it, I don't know how to do it.)

**Comment by tyshiwo1** [comment] 2024-06-04 10:51
> wow，Do you know how to change this line of code (acc += tl.dot(cb, dout)) to solve the nan problem? (I'm so bad at it, I don't know how to do it.)

I am trying on it. Also, the code around this line may also cause bug.
Besides, other variables like `ddt_bias` also contain NaN. Maybe a lot of codes need to change.

**Comment by zzzendurance** [comment] 2024-06-04 10:58
不明觉厉，我自己也研究研究。

那大佬你说这是因为mamba2本身的bug，还是说是因为大家把他用到了各自的任务上才出现了nan这样的问题（也就是说大家要根据自己的任务适当地 有针对性地修改代码？）？

**Comment by tyshiwo1** [comment] 2024-06-04 11:01
> 不明觉厉，我自己也研究研究。
> 
> 那大佬你说这是因为mamba2本身的bug，还是说是因为大家把他用到了各自的任务上才出现了nan这样的问题（也就是说大家要根据自己的任务适当地 有针对性地修改代码？）？

I apply Mamba2 on image generation instead of NLP tasks, and get NaN loss.

**Comment by tridao** [comment] 2024-06-04 13:50
Would be hard for us to say what's causing NaN until we can reproduce it. Can you save all the tensors right before the function call that produced NaN and share with us?
Sth like
```
if dx.isnan().any():
    # save tensors to disk with torch.save
```
So that we can reproduce it like this:
```
# load x, b, c, dt, etc from disk with torch.load
# whatever function here that caused NaN
# we observe NaN in dx for example.
```

**Comment by bio-mlhui** [comment] 2024-06-04 14:25
A smaller A range (close to 1) and a smaller chunk size may make the training more stable

**Comment by XiudingCai** [comment] 2024-06-04 15:34
> Would be hard for us to say what's causing NaN until we can reproduce it. Can you save all the tensors right before the function call that produced NaN and share with us? Sth like
> 
> ```
> if dx.isnan().any():
>     # save tensors to disk with torch.save
> ```
> 
> So that we can reproduce it like this:
> 
> ```
> # load x, b, c, dt, etc from disk with torch.load
> # whatever function here that caused NaN
> # we observe NaN in dx for example.
> ```

Hi Tri, I'm encountering NaN outputs when training a model with the following parameters:

d_model=512
d_state=64
headdim=16
chunk_size=256 (default)
This issue occurs when using the default chunk_size=256. However, when I follow @bio-mlhui's suggestion and set chunk_size=1, the NaN outputs disappear, and the training proceeds normally. This suggests that the chunk_size value might be the culprit.

**Comment by tyshiwo1** [comment] 2024-06-04 15:50
> Would be hard for us to say what's causing NaN until we can reproduce it. Can you save all the tensors right before the function call that produced NaN and share with us? Sth like
> 
> ```
> if dx.isnan().any():
>     # save tensors to disk with torch.save
> ```
> 
> So that we can reproduce it like this:
> 
> ```
> # load x, b, c, dt, etc from disk with torch.load
> # whatever function here that caused NaN
> # we observe NaN in dx for example.
> ```

Thank you for your reply !!!
I have uploaded my tensors to [Google drive](https://drive.google.com/drive/folders/1ojmQNDsAToNZaP3ZNOAeMJBu1AshMnXS?usp=sharing).

The error occurs on [this line](https://github.com/state-spaces/mamba/blob/26283fbfa16dd0c2e054aab3f140ce10d3d02e6e/mamba_ssm/ops/triton/ssd_combined.py#L403), so I save the input and output tensors.

I also tried some operations like changing
```
dA_cs_k = tl.load(dA_cumsum_ptrs, mask=offs_k < K_MAX - k, other=0.0).to(tl.float32)
```
into 
```
dA_cs_k = tl.load(dA_cumsum_ptrs, mask=offs_k < K_MAX - k, other=-1e6).to(tl.float32)
```
, but this does not work on other variables like `dout`.

**Comment by XiudingCai** [comment] 2024-06-05 03:10
> A smaller A range (close to 1) and a smaller chunk size may make the training more stable

Thanks for the suggestion, I set the chunk_size to 1 and then the time of the NaN appeared backward, but it still appeared as a NaN.

**Comment by XiudingCai** [comment] 2024-06-05 10:08
> I think `chunk_size` does not really matter. Emperically I found set `A_init_range` to (1, 1.1) works for me.

It did.

**Comment by tyshiwo1** [comment] 2024-06-05 11:49
> I think `chunk_size` does not really matter. Emperically I found set `A_init_range` to (1, 1.1) works for me.

This can stabilize the training of the first few iterations, but the loss becomes NaN later.

**Comment by tyshiwo1** [comment] 2024-06-05 13:49
> same issue. In my code, the loss suddenly becomes nan. 

Maybe you can also locate the NaN values and provide the tensors like I did 😂.

**Comment by bio-mlhui** [comment] 2024-06-05 20:13
if it is still not stable, the last method is to lower down the learning rate

**Comment by ZijianYY** [comment] 2024-06-06 03:34
> > same issue. In my code, the loss suddenly becomes nan.
> 
> Maybe you can also locate the NaN values and provide the tensors like I did 😂.

Checked. It is also the ddt_bias tensor as you mentioned before.
<img width="489" alt="ddt_bias" src="https://github.com/state-spaces/mamba/assets/119492445/50f19f34-1cff-4749-a51a-842db94b3ee5">

**Comment by ZijianYY** [comment] 2024-06-06 03:41
> if it is still not stable, the last method is to lower down the learning rate

Tried. The result is just the same as decreasing chunk size. It can stabilize for more epochs but loss becomes nan later.

**Comment by tyshiwo1** [comment] 2024-06-06 07:05
> Would be hard for us to say what's causing NaN until we can reproduce it. Can you save all the tensors right before the function call that produced NaN and share with us? Sth like
> 
> ```
> if dx.isnan().any():
>     # save tensors to disk with torch.save
> ```
> 
> So that we can reproduce it like this:
> 
> ```
> # load x, b, c, dt, etc from disk with torch.load
> # whatever function here that caused NaN
> # we observe NaN in dx for example.
> ```

@ZijianYY You can follow the instructions here.

**Comment by EddieEduardo** [comment] 2024-06-09 15:02
Same here, raised nan when training using Mamba2

**Comment by catalpaaa** [comment] 2024-06-10 06:02
> > 不明觉厉，我自己也研究研究。
> > 那大佬你说这是因为mamba2本身的bug，还是说是因为大家把他用到了各自的任务上才出现了nan这样的问题（也就是说大家要根据自己的任务适当地 有针对性地修改代码？）？
> 
> I apply Mamba2 on image generation instead of NLP tasks, and get NaN loss.

i also get NaN on image classification taks :(

**Comment by zzzendurance** [comment] 2024-06-10 13:00
> > > 不明觉厉，我自己也研究研究。
> > > 那大佬你说这是因为mamba2本身的bug，还是说是因为大家把他用到了各自的任务上才出现了nan这样的问题（也就是说大家要根据自己的任务适当地 有针对性地修改代码？）？
> > 
> > 
> > I apply Mamba2 on image generation instead of NLP tasks, and get NaN loss.
> 
> i also get NaN on image classification taks :(

So is this problem still unresolved?（i get NaN on voice classification tasks）

**Comment by tridao** [comment] 2024-06-12 06:39
Thanks for the bug reports. We were able to reproduce the NaN gradients when sequence length is not a multiple of 256. We pushed a fix, can you guys try v2.0.4?

**Comment by EddieEduardo** [comment] 2024-06-12 06:42
My sequence length is 256， my task is object detection, it raised nan 😭

---- Replied Message ----
| From | Tri ***@***.***> |
| Date | 06/12/2024 14:39 |
| To | state-spaces/mamba ***@***.***> |
| Cc | EddieEduardo ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [state-spaces/mamba] Loss NaN in Mamba2 (Issue #352) |

Thanks for the bug reports. We were able to reproduce the NaN gradients when sequence length is not a multiple of 256. We pushed a fix, can you guys try v2.0.4?

**Comment by tridao** [comment] 2024-06-12 06:49
> My sequence length is 256， my task is object detection, it raised nan 😭
> […](#)
> ---- Replied Message ---- | From | Tri ***@***.***> | | Date | 06/12/2024 14:39 | | To | state-spaces/mamba ***@***.***> | | Cc | EddieEduardo ***@***.***>, Comment ***@***.***> | | Subject | Re: [state-spaces/mamba] Loss NaN in Mamba2 (Issue #352) | Thanks for the bug reports. We were able to reproduce the NaN gradients when sequence length is not a multiple of 256. We pushed a fix, can you guys try v2.0.4? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Please make a reproducible script (e.g. save the tensors right before the function that causes NaN). If we can't reproduce we can't do anything.

**Comment by tyshiwo1** [comment] 2024-06-12 08:12
> Thanks for the bug reports. We were able to reproduce the NaN gradients when sequence length is not a multiple of 256. We pushed a fix, can you guys try v2.0.4?

Thank you! We will try it.

**Comment by tyshiwo1** [comment] 2024-06-12 12:04
> > Thanks for the bug reports. We were able to reproduce the NaN gradients when sequence length is not a multiple of 256. We pushed a fix, can you guys try v2.0.4?
> 
> Thank you! We will try it.

This fix works for me. At least the loss remains stable over a few thousand training iterations. Thanks again!

**Comment by catalpaaa** [comment] 2024-06-12 13:34
> Thanks for the bug reports. We were able to reproduce the NaN gradients when sequence length is not a multiple of 256. We pushed a fix, can you guys try v2.0.4?

Huge fix, training works on d_model = 256 and 512. but once I lower d_model down to 192, the error
```
RuntimeError: causal_conv1d with channel last layout requires strides (x.stride(0) and x.stride(2)) to be multiples of 8
```
is produced, if I follow #362 to force the training to run, it will produce nan on any d_model.

Any plan on fixing this issue? Let me know what you need.

**Comment by Maykeye** [comment] 2024-06-12 13:35
> We pushed a fix, can you guys try v2.0.4?

Works now!

**Comment by catalpaaa** [comment] 2024-06-14 02:24
> > Thanks for the bug reports. We were able to reproduce the NaN gradients when sequence length is not a multiple of 256. We pushed a fix, can you guys try v2.0.4?
> 
> Huge fix, training works on d_model = 256 and 512. but once I lower d_model down to 192, the error
> 
> ```
> RuntimeError: causal_conv1d with channel last layout requires strides (x.stride(0) and x.stride(2)) to be multiples of 8
> ```
> 
> was produced, if I follow #362 to force the training to run, it will produce nan on any d_model.
> 
> Any plan on fixing this issue? Let me know what you need.

my bad for not investigate further, your fix is perfect and we should not use #362 with it, all we need is to make sure d_model * expand / headdim = multiple of 8

**Comment by TimothyChen225** [comment] 2024-06-17 02:36
> 1. my casual conv 1d version is 1.2.2.post1
> 2. I download the whole project and compile it locally using `CAUSAL_CONV1D_FORCE_BUILD=TRUE pip install --user -e .`

yes ,it did work for me

**Closed** 2024-06-18 15:00 UTC

**Comment by drhuangliwei** [comment] 2024-07-28 08:46
> I think `chunk_size` does not really matter. Emperically I found set `A_init_range` to (1, 1.1) works for me.

After running for a while, Nan is restored
